export { ArticlesDetailPageAsync as ArticlesDetailPage } from './ui/ArticlesDetailPage/ArticlesDetailPage.async'
export type { ArticleDetailsCommentsSchema } from './model/types/ArticleDetailsCommentsSchema'
export type { ArticleDetailsPageRecommendationsSchema } from './model/types/articleDetailsPageRecommendationsSchema'
export type { ArticlesDetailsPageSchema } from './model/types/index'
export { getCanEditArticle } from './model/selectors/article'
